# INSTALL & UPGRADE OS PACKAGES

# INSTALL CONSUL + NOMAD

- hosts: all
  become: yes
  roles:
    - ansible-role-consul
    - ansible-role-dnsmasq
    - ansible-role-nomad

- hosts: client
  become: yes
  roles:
    - ansible-role-docker
